name: Deploy to Firebase

on: [push]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: npm install in Nuxt.js
        run: npm i

      - name: Nuxt generate
        run: npm run generate

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: japan-bugbounty-forums